# Generated by Django 5.1.15 on 2026-04-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='forum_post_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
