# Generated by Django 5.1.15 on 2026-04-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recipe_calories_recipe_image_recipe_servings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
