# Generated by Django 5.1.15 on 2026-03-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_comment_likes_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('recipe', 'Przepis'), ('question', 'Pytanie')], default='question', max_length=20),
        ),
    ]
