# Generated by Django 5.1.15 on 2026-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('recipe', 'Przepis'), ('question', 'Porada')], default='recipe', max_length=20),
        ),
    ]
