# Generated by Django 5.1.15 on 2026-04-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('recipe', 'Przepis'), ('question', 'Porada')], default='recipe', max_length=20),
        ),
    ]
