# Generated by Django 5.1.15 on 2026-04-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_post_post_type'),
        ('forum', '0010_post_calories_post_ingredients_post_servings_and_more'),
    ]

    operations = [
    ]
