# Generated by Django 5.1.15 on 2026-04-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_merge_20260411_1138'),
        ('forum', '0011_merge_20260414_0825'),
    ]

    operations = [
    ]
