# Generated by Django 5.1.15 on 2026-04-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_merge_20260414_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Post body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
